name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc gdb binutils build-essential libelf-dev libdwarf-dev libzstd-dev elfutils

    - name: Build hugify
      run: |
        mkdir -p bin
        gcc -o bin/hugifyr -I/usr/include/libdwarf src/hugifyr.c -lelf -ldwarf -lz -lzstd

    - name: Run tests 
      run: |
        cd tests
        python3 test.py

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: |
          tests/test1.exe
          tests/test1_huge.exe
          tests/libtest1.so
          tests/libtest1_huge.so
